version: 2.1

node: &node
  docker:
    - image: circleci/node:stretch

gcp: &gcp
  docker:
    - image: google/cloud-sdk

root: &root
  working_directory: ~/drinking-microcomputer

at_front: &at_front
  working_directory: ~/drinking-microcomputer/front

jobs:
  build-front:
    <<: *node
    <<: *root
    steps:
      - checkout
      - restore_cache:
          keys:
            - drinking-microcomputer-{{ .Branch }}-{{ checksum "front/yarn.lock" }}
            - drinking-microcomputer-{{ .Branch }}
      - run:
          name: yarn install
          command: yarn install
          <<: *at_front
      - save_cache:
          key: drinking-microcomputer-{{ .Branch }}-{{ checksum "front/yarn.lock" }}
          paths:
            - "node_modules"
      - run:
          name: build
          command: yarn build
          <<: *at_front
      - persist_to_workspace:
          root: ~/drinking-microcomputer/front
          paths:
            - public/js

  deploy-front:
    <<: *gcp
    <<: *root
    steps:
      - checkout
      - run:
          name: init gcp
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - attach_workspace:
          at: ~/drinking-microcomputer/front
      - run:
          name: install package
          command: |
            apt update
            apt install -y make
      - run:
          name: initial ssh
          command: gcloud compute ssh dragontaro@test2 --quiet --strict-host-key-checking=no --command "echo success!"
      - run:
          name: deploy
          command: make deploy
          <<: *at_front

workflows:
  version: 2.1
  front-build:
    jobs:
      - build-front
  front-deploy:
    jobs:
      - build-front:
          filters:
            branches:
              only:
                - feature/ci
      - deploy-front:
          requires:
            - build-front
