---
- hosts: all
  become: true

  vars:
    host_name: drinking.dragon-taro.dev
    ansible_ssh_private_key_file: ~/.ssh/google_compute_engine
    letsencrypt_email: dragon.taro.lioil@gmail.com
    letsencrypt_cert_domains:
      - drinking.dragon-taro.dev
    letsencrypt_renewal_command_args: '--renew-hook "systemctl restart nginx"'
    nodejs_version: "10.x"

  tasks:
    - name: mkdir front
      file: path=./front state=directory owner=dragontaro group=dragontaro

    - name: install rsync
      apt: name=rsync

  roles:
    - thefinn93.letsencrypt
    - nginx
    - server
    - geerlingguy.nodejs
    - ws
