tar:
	gsutil cp gs://tar-for-deploy/server/dist.tgz .
	sudo tar -xzvf dist.tgz
	rm dist.tgz
	sudo mv ./dist ./server
	sudo rsync -ac ./server /var/www
	sudo rm -rf server

run: tar
	sudo systemctl restart server
