---
# tasks file for server
- name: install make
  apt: name=make update_cache=yes cache_valid_time=3600

- name: download Makefile
  command: gsutil cp gs://tar-for-deploy/Makefile .

- name: download server app
  command: make tar

- name: copy server systemd file
  template: src=templates/server.service.j2 dest=/etc/systemd/system/server.service

- name: start server
  service: name=server state=started
