---
# tasks file for server
- name: mkdir ws
  file: path=./ws state=directory owner=dragontaro group=dragontaro

- name: download Makefile
  command: gsutil cp gs://tar-for-deploy/ws/Makefile ./ws/

- name: chmod
  file: path=./ws/Makefile owner=dragontaro group=dragontaro

- name: download ws app
  command: chdir=./ws make tar

- name: copy server systemd file
  template: src=templates/ws.service.j2 dest=/etc/systemd/system/ws.service

- name: start server
  systemd:
    name: ws.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes
